global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "mysqld"
    static_configs:
      - targets: ["mysqld_exporter:9104"]

rule_files:
  - "alert.rules.yml"
