name: test-ssh-local
on: { workflow_dispatch: {} }

jobs:
  test-ssh:
    runs-on: [self-hosted]
    env:
      SSH_HOST: "127.0.0.1"
      SSH_USER: "tor"
      SSH_PORT: "2222" 
    steps:
      - name: Prepare key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -lf ~/.ssh/id_ed25519

      - name: Trust localhost
        run: |
          ssh-keyscan -T 5 -p "$SSH_PORT" -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Test via OpenSSH
        run: |
          ssh -p "$SSH_PORT" -i ~/.ssh/id_ed25519 "$SSH_USER@$SSH_HOST" \
            "echo ✅ OpenSSH OK; whoami; hostname; uptime"
