name: test-ssh
on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: 2222

    steps:
      - name: Which host is GH hitting?
        shell: bash
        run: ssh-keyscan -p "${SSH_PORT:-22}" -H "${SSH_HOST}" | ssh-keygen -lf -


      - name: Prepare SSH key (handle CRLF) & show fingerprint
        shell: bash
        run: |
          set -e
          mkdir -p ~/.ssh
          # กัน \r จาก Windows ที่อาจทำคีย์เพี้ยน
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "🔑 Private key fingerprint:"
          ssh-keygen -lf ~/.ssh/id_ed25519 || true

      - name: Best-effort known_hosts (optional)
        shell: bash
        run: |
          for i in {1..6}; do
            ssh-keyscan -T 5 -p "${SSH_PORT:-22}" -H "$SSH_HOST" >> ~/.ssh/known_hosts && break || sleep 3
          done || true

      - name: Test via OpenSSH (เหมือนต่อจากเทอร์มินัล)
        shell: bash
        run: |
          set -x
          ssh -vvv \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -o ServerAliveInterval=10 \
            -o ServerAliveCountMax=3 \
            -p "${SSH_PORT:-22}" \
            -i ~/.ssh/id_ed25519 \
            "$SSH_USER@$SSH_HOST" \
            "echo '✅ OpenSSH OK'; whoami; hostname; uptime"

      - name: Test via appleboy/ssh-action (ทางเลือก)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          port: ${{ env.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ appleboy OK"
            whoami
            hostname
            uptime
