name: Test SSH
on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets
        run: |
          test -n "${{ secrets.SSH_HOST }}" || (echo "❌ SSH_HOST missing" && exit 1)
          test -n "${{ secrets.SSH_USER }}" || (echo "❌ SSH_USER missing" && exit 1)
          test -n "${{ secrets.SSH_KEY }}"  || (echo "❌ SSH_KEY missing" && exit 1)

      - name: SSH connect
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "✅ SSH Connected!"
            hostname
            uptime
            exit 0