name: Test SSH
on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Prepare key & known_hosts
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # บันทึกลายนิ้วมือไว้ดูใน logs (ไม่เปิดเผยตัวคีย์)
          ssh-keygen -lf ~/.ssh/id_ed25519
          # ดึง host key เพื่อป้องกันถาม yes/no ตอนเชื่อมต่อ
          ssh-keyscan -p "${SSH_PORT:-22}" -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Test via OpenSSH (direct)
        run: |
          ssh -p "${SSH_PORT:-22}" -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes \
            "$SSH_USER@$SSH_HOST" "echo 

      - name: Test via appleboy/ssh-action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          port: ${{ env.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ appleboy OK"
            whoami
            hostname
            uptime
